# Generated by Django 5.1.7 on 2026-04-01 13:01

import blog.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import mptt.fields
import simple_history.models
import taggit.managers
import utils.custom_fields.slug_field
import utils.validate.validators_image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('slug', utils.custom_fields.slug_field.AutoSlugField(editable=False, max_length=255, unique=True, verbose_name='آدرس دسته بندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن/نبودن')),
                ('is_special', models.BooleanField(default=False, verbose_name='وضعیت ویژه بودن/نبودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.articlecategory', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی های مقاله',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مقاله')),
                ('slug', utils.custom_fields.slug_field.AutoSlugField(editable=False, max_length=255, unique=True, verbose_name='آدرس مقاله')),
                ('sv', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('banner', models.ImageField(upload_to=blog.models.get_upload_banner, validators=[utils.validate.validators_image.validate_image_size], verbose_name='بنر مقاله')),
                ('content', models.JSONField(verbose_name='محتوای مقاله')),
                ('short_description', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_published', models.BooleanField(default=False, verbose_name='وضعیت انتشار')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='وضعیت حذف')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده مقاله')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب ها')),
                ('categories', models.ManyToManyField(db_table='article_category_link', related_name='articles', to='blog.articlecategory', verbose_name='دسته بندی های مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Article/images/', validators=[utils.validate.validators_image.validate_image_size])),
                ('alt_text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ترتیب تصویر')),
                ('upload_session', models.UUIDField(blank=True, db_index=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Image',
                'verbose_name_plural': 'Article Images',
            },
        ),
        migrations.CreateModel(
            name='ArticleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('add', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('need_revision', 'نیاز به اصلاح'), ('draft', 'پیش نویس')], default='draft', max_length=20)),
                ('data', models.JSONField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('need_revision', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_article_requests', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalArticleRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('add', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('need_revision', 'نیاز به اصلاح'), ('draft', 'پیش نویس')], default='draft', max_length=20)),
                ('data', models.JSONField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('need_revision', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admin', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical درخواست',
                'verbose_name_plural': 'historical درخواست ها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='articlecategory',
            index=models.Index(fields=['slug'], name='blog_articl_slug_f4e2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sv'], name='blog_articl_sv_766336_gin'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_deleted', 'is_published'], name='blog_articl_is_dele_9e0ee5_idx'),
        ),
    ]
