# Generated by Django 5.1.7 on 2026-03-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['priority', 'id', 'created_at'], 'verbose_name': 'دسته بندی مقاله', 'verbose_name_plural': 'دسته بندی های مقاله'},
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='هر چه عدد کمتر باشد، در لیست بالاتر نمایش داده می\u200cشود', verbose_name='اولویت نمایش'),
        ),
    ]
