# Generated by Django 5.1.7 on 2026-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, help_text='هر چه عدد کمتر باشد، در لیست بالاتر نمایش داده می\u200cشود', null=True, verbose_name='اولویت نمایش'),
        ),
    ]
