# Generated by Django 5.1.7 on 2026-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articlecategory_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerequest',
            name='action',
            field=models.CharField(choices=[('add', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalarticlerequest',
            name='action',
            field=models.CharField(choices=[('add', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20),
        ),
    ]
