# Generated by Django 5.1.7 on 2025-05-03 14:47

import courses.models
import datetime
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import mptt.fields
import simple_history.models
import taggit.managers
import utils.custom_fields.slug_field
import utils.validate.validators_image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=250, verbose_name='آدرس دسته بندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن/نبودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.coursecategory', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی دوره',
                'verbose_name_plural': 'دسته بندی های دوره',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('slug', utils.custom_fields.slug_field.AutoSlugField(editable=False, max_length=255, unique=True, verbose_name='آدرس دوره')),
                ('sv', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('language', models.CharField(choices=[('az', 'ترکی آذربایجانی')], max_length=50, verbose_name='زبان دوره')),
                ('prerequisites', models.CharField(blank=True, max_length=100, null=True, verbose_name='پیش نیاز')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=courses.models.get_upload_banner, validators=[utils.validate.validators_image.validate_image_size], verbose_name='بنر دوره')),
                ('url_video', models.URLField(blank=True, help_text='این فیلد برای ویدیوهای کوتاه و آشنایی با دوره یا معرفی استاد است.', null=True, unique=True, verbose_name='لینک ویدیو')),
                ('status', models.CharField(choices=[('COMPLETED', 'تکمیل شده'), ('IN_PROGRESS', 'در حال برگذاری'), ('UPCOMING', 'به زودی'), ('CANCELLED', 'لغو شده')], max_length=30, verbose_name='وضعیت دوره')),
                ('count_students', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد دانشجویان')),
                ('count_lessons', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد درس ها')),
                ('count_comments', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد نظر ها')),
                ('duration', models.DurationField(default=datetime.timedelta(0), editable=False, verbose_name='مدت زمان دوره')),
                ('is_published', models.BooleanField(default=False, verbose_name='وضعیت انتشار')),
                ('has_seasons', models.BooleanField(default=False, verbose_name='فصل بندی شده/نشده')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='وضعیت حذف')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع دوره')),
                ('last_lesson_update', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ آخرین بروزرسانی جلسات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ انتشار')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب ها')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس دوره')),
                ('categories', models.ManyToManyField(related_name='courses', to='courses.coursecategory', verbose_name='دسته بندی دوره')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
                'ordering': ['published_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('lesson', 'درس'), ('feature', 'ویژگی'), ('faq', 'سوالات متداول'), ('season', 'فصل'), ('course', 'دوره')], max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('add', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('need_revision', 'نیاز به اصلاح'), ('draft', 'پیش نویس')], default='draft', max_length=20)),
                ('data', models.JSONField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('need_revision', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_course_requests', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ترتیب دوره')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='وضعیت حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='توضیحات')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ترتیب دوره')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='وضعیت حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
                'ordering': ['order', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCourseRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('lesson', 'درس'), ('feature', 'ویژگی'), ('faq', 'سوالات متداول'), ('season', 'فصل'), ('course', 'دوره')], max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('add', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('need_revision', 'نیاز به اصلاح'), ('draft', 'پیش نویس')], default='draft', max_length=20)),
                ('data', models.JSONField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('need_revision', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admin', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical درخواست',
                'verbose_name_plural': 'historical درخواست ها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LearningLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام سطح آموزشی')),
                ('level_number', models.PositiveSmallIntegerField(unique=True, verbose_name='شماره سطح آموزشی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن/نبودن')),
            ],
            options={
                'verbose_name': 'سطح آموزشی',
                'verbose_name_plural': 'سطوح آموزشی',
                'ordering': ['level_number'],
                'unique_together': {('name', 'level_number')},
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن/نبودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('end_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths_end', to='courses.learninglevel', verbose_name='پایان سطح آموزشی')),
                ('start_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths_start', to='courses.learninglevel', verbose_name='شروع سطح آموزشی')),
            ],
            options={
                'verbose_name': 'مسیر آموزشی',
                'verbose_name_plural': 'مسیرهای آموزشی',
                'ordering': ['start_level', 'end_level'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.learningpath', verbose_name='سطح مسیر آموزشی'),
        ),
        migrations.CreateModel(
            name='LessonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=courses.models.get_upload_videos)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=courses.models.get_upload_attachments)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='courses.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رسانه\u200cی درس',
                'verbose_name_plural': 'رسانه\u200cهای درس',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_price', models.PositiveIntegerField(verbose_name='قیمت اصلی')),
                ('discount_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('final_price', models.PositiveIntegerField(editable=False, verbose_name='قیمت نهایی')),
                ('discount_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای تخفیف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان فصل')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ترتیب دوره')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='وضعیت حذف')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان فصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل ها',
                'ordering': ['order', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان درس')),
                ('url_video', models.URLField(unique=True, verbose_name='آدرس ویدیو')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ترتیب دوره')),
                ('url_attachment', models.URLField(blank=True, null=True, unique=True, verbose_name='آدرس فایل ها')),
                ('is_published', models.BooleanField(default=False, verbose_name='وضعیت انتشار')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='وضعیت حذف')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان فصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ انتشار')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='دوره')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.season', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس ها',
                'ordering': ['order', 'published_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='coursecategory',
            index=models.Index(fields=['slug'], name='courses_cou_slug_6be797_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecategory',
            unique_together={('title', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='learningpath',
            unique_together={('start_level', 'end_level')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sv'], name='courses_cou_sv_6d29c9_gin'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_deleted', 'is_published'], name='courses_cou_is_dele_18a4ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title', 'slug')},
        ),
    ]
